### ISSUE TITLE
 weights for the trained model?

### ISSUE THREAD

**Issue by isalirezag** [Feynman27/pytorch-detect-rfcn#1]
Can you provide the weights that got 70% mAP on VID dataset?

**Comment by Feynman27** [comment]
Here's my public Google drive of the models: [models](https://drive.google.com/drive/folders/1TM9bJ1mod2EipgXHhYscRxkJhrtOGSju?usp=sharing). They are referenced in the detect-to-track repo but I must have forget to reference the trained model in this repo.
