### ISSUE TITLE
regarding DET and VID datasets

### ISSUE THREAD

**Issue by isalirezag** [Feynman27/pytorch-detect-rfcn#2]
can you please tell us what version of DET and VID are you using?
It would be also very useful if you can provide a link to their source to download them please

Also when you mentioned that data should be in form of:

```
|--ILSVRC2015
|----Annotations
|------DET
|--------train
|--------val
|------VID
|--------train
|--------val
|----Data
|------DET
|--------train
|--------val
|------VID
|--------train
|--------val
|----ImageSets
|------DET
|------VID
```

can you clarify how they should be inside ```train``` and ```val```? 
I mean should it be like folders for each video or all the frames? and the same for DET.
Thanks :)

**Comment by Feynman27** [comment]
Yes, this is the expected directory structure. I'll find time next weekend/week to upload the DET and VID datasets that I used.

**Comment by isalirezag** [comment]
Thank you so much!

**Comment by isalirezag** [comment]
Thanks a lot!

**Comment by isalirezag** [comment]
can i have a follow up question?
When you use DET, do you just consider the classes that are in VID, OR you use all 1000 classes in DET and use the one that are not in the VID as background?
Thanks :)

**Comment by Feynman27** [comment]
I just used the intersection of the classes in DET and VID.

**Comment by Feynman27** [comment]
Here's a link to the train/val/test splits in ILSVRC2015 that I used: [here](https://drive.google.com/drive/u/0/folders/1TM9bJ1mod2EipgXHhYscRxkJhrtOGSju)
