### ISSUE TITLE
Error while trying to test the model

### ISSUE THREAD

**Issue by isalirezag** [Feynman27/pytorch-detect-rfcn#3]
I used the saved model that you provided online (```rfcn_detect.pth```) and made the dataset as you mentioned. 
Now I just want to test the model and get the mentioned mAP. However, when i run the test_net.py file i face  the following error 

`RuntimeError: While copying the parameter named RFCN_bbox_net.weight, whose dimensions in the model are torch.Size([6076, 512, 1, 1]) and whose dimensions in the checkpoint are torch.Size([196, 512, 1, 1]).`

I did not change anything in the code.  am i doing something wrong?
Do you any suggestion in that regard?

Thanks

**Comment by Feynman27** [comment]
I'll have to take a closer look, but the 196 comes from the 7 x 7 RoI pooling bins with 4 box coordinates. These represent bbox coordinates per roi, as described in the original paper. The regression is class-agnostic.

**Comment by isalirezag** [comment]
I think the reason might be because the provided weights are for the detect and track model, while i was trying to use that weight for the rfcn model.
I am trying to download the DET and VID dataset and train the model then  just save it and check to see why it happened.
I will update you if i solved it.
Thanks

**Comment by Feynman27** [comment]
Sorry about that. I'll see if I can locate the RFCN weights.

**Comment by jmsinusa** [comment]
Did you find the weights for the RFCN model?

**Comment by xjtuwh** [comment]
I meet the same trouble "RuntimeError: While copying the parameter named RFCN_bbox_net.weight, whose dimensions in the model are torch.Size([6076, 512, 1, 1]) and whose dimensions in the checkpoint are torch.Size([196, 512, 1, 1])." The model can be used to demo.py. Since 196*31=6076, when running test_net.py, we should set the argument parameter "--cag".

**Comment by PyNancy** [comment]
> I used the saved model that you provided online (`rfcn_detect.pth`) and made the dataset as you mentioned.
> Now I just want to test the model and get the mentioned mAP. However, when i run the test_net.py file i face the following error
> 
> `RuntimeError: While copying the parameter named RFCN_bbox_net.weight, whose dimensions in the model are torch.Size([6076, 512, 1, 1]) and whose dimensions in the checkpoint are torch.Size([196, 512, 1, 1]).`
> 
> I did not change anything in the code. am i doing something wrong?
> Do you any suggestion in that regard?
> 
> Thanks

Hi, about your meeting trouble,are your solved it? i meet the same trouble,if you give me some suggest,i am will thanks for you.

**Comment by xjtuwh** [comment]
when running test_net.py, we should set the argument parameter "--cag".
